apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operator.group }}
  namespace: {{ .Values.operator.namespace }}
spec:
{{- if not .Values.operator.clusterScoped -}}
  targetNamespaces:
  - {{ .Values.operator.namespace }}
{{- end -}}
